# Generated by Django 5.1.1 on 2026-09-05 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="description",
        ),
        migrations.AddField(
            model_name="exercise",
            name="aliases",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="alternatives",
            field=models.ManyToManyField(
                blank=True, related_name="alternative_for", to="gym_api.exercise"
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="animation_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="body_part",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Chest", "Chest"),
                    ("Back", "Back"),
                    ("Shoulders", "Shoulders"),
                    ("Arms", "Arms"),
                    ("Legs", "Legs"),
                    ("Core", "Core"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="breathing",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="common_mistakes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="equipment",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="execution",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Compound", "Compound"),
                    ("Isolation", "Isolation"),
                    ("Bodyweight", "Bodyweight"),
                    ("Machine", "Machine"),
                    ("Cardio", "Cardio"),
                    ("Mobility", "Mobility"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="exercises/"),
        ),
        migrations.AddField(
            model_name="exercise",
            name="instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="is_library",
            field=models.BooleanField(
                default=False,
                help_text="True when this exercise is part of the global library",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="movement_pattern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Horizontal Push", "Horizontal Push"),
                    ("Vertical Push", "Vertical Push"),
                    ("Horizontal Pull", "Horizontal Pull"),
                    ("Vertical Pull", "Vertical Pull"),
                    ("Squat", "Squat"),
                    ("Lunge", "Lunge"),
                    ("Hinge", "Hinge"),
                    ("Isolation", "Isolation"),
                    ("Core Stabilization", "Core Stabilization"),
                    ("Rotation", "Rotation"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="primary_muscles",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="progression_exercises",
            field=models.ManyToManyField(
                blank=True, related_name="progression_for", to="gym_api.exercise"
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="regression_exercises",
            field=models.ManyToManyField(
                blank=True, related_name="regression_for", to="gym_api.exercise"
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="secondary_muscles",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="setup",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(fields=["name"], name="exercises_name_26c749_idx"),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["body_part"], name="exercises_body_pa_7cfae5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["movement_pattern"], name="exercises_movemen_16a4d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["difficulty"], name="exercises_difficu_bf8baf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(
                fields=("name", "plan", "user"), name="unique_exercise_per_owner"
            ),
        ),
    ]
