# Generated by Django 5.1.1 on 2026-09-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="exercises/"),
        ),
    ]
