# Generated by Django 5.1.1 on 2026-09-06 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0005_exercise_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="gym_api.plan",
                    ),
                ),
            ],
            options={
                "db_table": "plan_days",
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="PlanDayExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_day_assignments",
                        to="gym_api.exercise",
                    ),
                ),
                (
                    "plan_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="gym_api.planday",
                    ),
                ),
            ],
            options={
                "db_table": "plan_day_exercises",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="planday",
            constraint=models.UniqueConstraint(
                fields=("plan", "weekday"), name="unique_plan_weekday"
            ),
        ),
        migrations.AddConstraint(
            model_name="planday",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                name="plan_day_weekday_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="plandayexercise",
            constraint=models.UniqueConstraint(
                fields=("plan_day", "exercise"), name="unique_exercise_per_plan_day"
            ),
        ),
    ]
