# Generated by Django 5.1.1 on 2026-09-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gym_api",
            "0006_planday_plandayexercise_planday_unique_plan_weekday_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutsession",
            name="scheduled_for",
            field=models.DateField(blank=True, null=True),
        ),
    ]
