# Generated by Django 5.1.1 on 2026-09-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0009_favoriteexercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="is_timed",
            field=models.BooleanField(default=False),
        ),
    ]
