# Generated by Django 5.1.1 on 2026-09-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0010_exercise_is_timed"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="availability",
            field=models.CharField(
                blank=True,
                help_text='Free-text preferred training times, e.g. "Weekday mornings, Sat afternoons".',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Short intro shown on the Gym Bro discovery card."
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="experience_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="training_goals",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of GOAL_CHOICES values, e.g. ["strength", "cardio"].',
                null=True,
            ),
        ),
    ]
