# Generated by Django 5.1.15 on 2026-09-08 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_api', '0011_profile_availability_profile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_bro_matches_high', to=settings.AUTH_USER_MODEL)),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_bro_matches_low', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gym_bro_matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymBroMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_bro_messages', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gym_api.match')),
            ],
            options={
                'db_table': 'gym_bro_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_bro_swipes_made', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_bro_swipes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gym_bro_swipes',
            },
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('user_low', 'user_high'), name='unique_gym_bro_match_pair'),
        ),
        migrations.AddConstraint(
            model_name='swipe',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_gym_bro_swipe_pair'),
        ),
    ]
