# Generated by Django 5.1.15 on 2026-09-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_api', '0012_match_gymbromessage_swipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(blank=True, choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Legs', 'Legs'), ('Core', 'Core'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Forearms', 'Forearms'), ('Quadriceps', 'Quadriceps'), ('Hamstrings', 'Hamstrings'), ('Glutes', 'Glutes'), ('Calves', 'Calves'), ('Abdominals', 'Abdominals'), ('Obliques', 'Obliques'), ('Lower Back', 'Lower Back'), ('Hip Flexors', 'Hip Flexors'), ('Adductors', 'Adductors'), ('Abductors', 'Abductors'), ('Traps', 'Traps'), ('Neck', 'Neck'), ('Full Body', 'Full Body'), ('Cardio', 'Cardio'), ('Other', 'Other')], max_length=50),
        ),
    ]
