# Generated by Django 5.1.15 on 2026-09-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_api', '0013_alter_exercise_body_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='animation',
            field=models.FileField(blank=True, null=True, upload_to='exercises/animations/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='exercises/videos/'),
        ),
    ]
