# Generated by Django 5.1.15 on 2026-09-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_api', '0014_exercise_animation_exercise_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Matches'},
        ),
    ]
