# Generated by Django 5.1.15 on 2026-09-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_api', '0015_alter_match_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
