# Generated by Django 5.1.15 on 2026-09-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_api', '0016_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='avatars/'),
        ),
    ]
