# Generated by Django 5.1.1 on 2026-09-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0017_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("trialing", "Trialing"),
                    ("active", "Active"),
                    ("past_due", "Past due"),
                    ("canceled", "Canceled"),
                    ("unpaid", "Unpaid"),
                    ("waitlisted", "Waitlisted for premium"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
