# Generated by Django 5.1.15 on 2026-09-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_api', '0018_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteexercise',
            options={'ordering': ['id']},
        ),
    ]
