# Generated by Django 5.1.15 on 2026-09-13 13:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_api', '0019_alter_favoriteexercise_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('sleep', 'Sleep'), ('stress_relief', 'Stress relief'), ('focus', 'Focus'), ('body_scan', 'Body scan'), ('breathing', 'Breathing')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meditation_sessions',
                'ordering': ['-completed_at'],
            },
        ),
    ]
