# Generated by Django 5.1.15 on 2026-09-13 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_api', '0020_meditationsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('bug', 'Bug report'), ('suggestion', 'Suggestion'), ('feature_request', 'Feature request'), ('other', 'Other')], default='other', max_length=20)),
                ('message', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='feedback/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
